cni:
  exclusive: false
  # readCniConf: /host/etc/cni/net.d/05-cilium.conf
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: '24'
    clusterPoolIPv4PodCIDRList:
    - 10.16.0.0/12
