apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: cilium
  name: netshoot2
  namespace: default
spec:
  containers:
  - name: netshoot
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
    image: nicolaka/netshoot
    imagePullPolicy: Always
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]
    resources:
      limits:
        memory: 80Mi
      requests:
        cpu: 1m
        memory: 40Mi
