apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "cilium" } ]'
  name: netshoot2
  namespace: default
spec:
  containers:
  - name: netshoot
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
    image: nicolaka/netshoot
    imagePullPolicy: Always
    resources:
      limits:
        memory: 80Mi
      requests:
        cpu: 1m
        memory: 40Mi
