apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cilium
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "type": "cilium-cni",
      "enable-debug": true,
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/16",
        "routes": [ { "dst": "0.0.0.0/0" } ],
        "gateway": "10.0.0.1"
      },
      "log-file":"/var/run/cilium/cilium-cni.log"
    }
